import React from 'react';

const Legal = () => {
  return (
    <section className="section" style={{ background: 'var(--background)' }}>
      <div className="container" style={{ maxWidth: '800px' }}>
        
        <div id="privacy" style={{ marginBottom: '4rem' }}>
          <h2 style={{ marginBottom: '1.5rem', color: 'var(--primary)' }}>Privacy Policy</h2>
          <div style={{ color: 'var(--text-muted)', lineHeight: '1.8' }}>
            <p><strong>Effective Date:</strong> {new Date().toLocaleDateString()}</p>
            <p>Welcome to CardioAI, built by Devansh. Your privacy is critically important to us. This Privacy Policy explains how we collect, use, and protect your personal information.</p>
            <h4 style={{ marginTop: '1rem', color: 'var(--text-main)' }}>1. Information We Collect</h4>
            <p>We only collect the medical and vital information you provide directly in the Analyzer form. This data is processed locally on your device and is optionally saved to your browser's Local Storage to show your history. We do not transmit your sensitive health data to external databases.</p>
            <h4 style={{ marginTop: '1rem', color: 'var(--text-main)' }}>2. How We Use Information</h4>
            <p>Your data is used strictly to compute a personalized heart risk assessment utilizing our heuristic scoring algorithms.</p>
            <h4 style={{ marginTop: '1rem', color: 'var(--text-main)' }}>3. Contacting Us</h4>
            <p>If you have questions about this privacy policy, please contact us at the details provided below.</p>
          </div>
        </div>

        <div id="terms">
          <h2 style={{ marginBottom: '1.5rem', color: 'var(--primary)' }}>Terms of Service</h2>
          <div style={{ color: 'var(--text-muted)', lineHeight: '1.8' }}>
            <p><strong>Effective Date:</strong> {new Date().toLocaleDateString()}</p>
            <p>By accessing or using the CardioAI application, you agree to be bound by these Terms of Service.</p>
            <h4 style={{ marginTop: '1rem', color: 'var(--text-main)' }}>1. Disclaimer of Medical Liability</h4>
            <p>CardioAI is designed for educational and informational purposes only. It is <strong>NOT</strong> a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider.</p>
            <h4 style={{ marginTop: '1rem', color: 'var(--text-main)' }}>2. Permitted Use</h4>
            <p>You may use this application for personal health tracking. Any automated data scraping, circumvention of security features, or reverse engineering of the heuristic models is strictly prohibited.</p>
            <h4 style={{ marginTop: '1rem', color: 'var(--text-main)' }}>3. Limitation of Liability</h4>
            <p>Devansh and CardioAI shall not be held liable for any decisions made based on the risk scores generated by this application.</p>
          </div>
        </div>

      </div>
    </section>
  );
};

export default Legal;
